kanban/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('kanban/', include('kanban.urls')),
    path('kanban/', include('django.contrib.auth.urls')), # 認証周りのルーティングはこれ一つで設定OK
    path('admin/', admin.site.urls),
]

kanban/kanban/urls.py
from django.urls import path

from . import views

# アプリ名を設定
app_name = 'kanban'

urlpatterns = [
    # path()関数
    # route  必須 URLパターン文字列
    # view   必須 ビュー関数 画面応答のアクションを指定する
    # name   任意 URL名称を定義
    # kwargs 任意 追加引数を辞書でビューに渡す時に指定する
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    # ユーザ
    path('users/<int:pk>/', views.UserDetailView.as_view(), name='users_detail'),
    path('users/<int:pk>/update/', views.UserUpdateView.as_view(), name='users_update'),
    # リスト
    path('lists/', views.ListListView.as_view(), name='lists_list'),
    path('lists/create/', views.ListCreateView.as_view(), name='lists_create'),
    path('lists/<int:pk>/', views.ListDetailView.as_view(), name='lists_detail'),
    path('lists/<int:pk>/update/', views.ListUpdateView.as_view(), name='lists_update'),
    path('lists/<int:pk>/delete/', views.ListDeleteView.as_view(), name='lists_delete'),
    # カード
    path('cards/', views.CardListView.as_view(), name='cards_list'),
    path('cards/create/', views.CardCreateView.as_view(), name='cards_create'),
    path('cards/<int:pk>/', views.CardDetailView.as_view(), name='cards_detail'),
    path('cards/<int:pk>/update/', views.CardUpdateView.as_view(), name='cards_update'),
    path('cards/<int:pk>/delete/', views.CardDeleteView.as_view(), name='cards_delete'),
]

kanban/kanban/models.py
from django.contrib.auth.models import User
from django.db import models


class List(models.Model):
  """
  リストのModelクラス
  """
  # タイトル
  title = models.CharField(max_length=200)
  # 作成ユーザ
  # ForeignKey()で１リスト：多ユーザを表現
  # models.CASCADEで紐づいたユーザが削除された時の挙動を指定 -> ユーザが削除されたらリストも削除される
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.title


class Card(models.Model):
  """
  カードのModelクラス
  """
  # タイトル
  title = models.CharField(max_length=200)
  # 説明文(テキスト型・文字数制限なし)
  description = models.TextField()
  # 作成ユーザ
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  # 紐づくリスト
  list = models.ForeignKey(List, on_delete=models.CASCADE)

  def __str__(self):
    return self.title

kanban/kanban/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import List, Card

class UserForm(forms.ModelForm):

  class Meta:
    model = User
    fields = ('username', 'last_name', 'first_name', 'email',)


class ListForm(forms.ModelForm):

  class Meta:
    model = List
    fields = ('title',)


class CardForm(forms.ModelForm):

  class Meta:
    model = Card
    fields = ('title', 'description', 'list',)

kanban/kanban/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, resolve_url
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView, CreateView, ListView, DeleteView

from .forms import UserForm, ListForm, CardForm
from .mixins import OnlyYouMixin
from .models import List, Card

def index(request):
    """
    トップページの初期表示
    indexというビューを定義
    """
    # テンプレートを指定せずに文字列を直接指定 文字列をレスポンスとして返すときはHttpResponse()関数を使用する
    # return HttpResponse('仮のトップページ')

    # テンプレートを指定するときはrender()関数で
    return render(request, 'kanban/index.html')


@login_required
def home(request):
    """
    ホーム画面の初期表示
    """
    return render(request, 'kanban/home.html')


def signup(request):
    """
    サインアップ画面
    """
    if request.method == 'POST':
        # 入力値を取得
        form = UserCreationForm(request.POST)
        # 入力値のバリデーション実行
        if form.is_valid():
            # データの永続化・モデルのインスタンスを取得
            user_instance = form.save()
            login(request, user_instance)
            return redirect('kanban:home')
    else:
        # フォームクラスのインスタンスを作成
        # →サインアップに必要な情報を入力するフォームを表示するため
        form = UserCreationForm()

    context = {
        'form': form
    }
    return render(request, 'kanban/signup.html', context)


# classで定義すると再利用可能な汎用クラスビューを継承して実装できる
# pythonではあまりオブジェクト指向的なクラスのイメージを持って書かない方がいいかもしれない、別物感がある
class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'kanban/users/detail.html'


class UserUpdateView(OnlyYouMixin, UpdateView):
    model = User
    template_name = 'kanban/users/update.html'
    form_class = UserForm

    # メソッド関数の宣言では、オブジェクト自体を表す第一引数を明示しなければなりません。
    # 第一引数のオブジェクトはメソッド呼び出しの際に暗黙の引数として渡されます。
    # https://docs.python.org/ja/3.8/tutorial/classes.html
    def get_success_url(self):
        return resolve_url('kanban:users_detail', pk=self.kwargs['pk'])


class ListCreateView(LoginRequiredMixin, CreateView):
    model = List
    template_name = 'kanban/lists/create.html'
    form_class = ListForm
    success_url = reverse_lazy('kanban:lists_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ListListView(LoginRequiredMixin, ListView):
    model = List
    template_name = 'kanban/lists/list.html'


class ListDetailView(LoginRequiredMixin, DetailView):
    model = List
    template_name = 'kanban/lists/detail.html'


class ListUpdateView(LoginRequiredMixin, UpdateView):
    model = List
    template_name = 'kanban/lists/update.html'
    form_class = ListForm

    def get_success_url(self):
        return resolve_url('kanban:lists_detail', pk=self.kwargs['pk'])


class ListDeleteView(LoginRequiredMixin, DeleteView):
    model = List
    template_name = 'kanban/lists/delete.html'
    form_class = ListForm
    success_url = reverse_lazy('kanban:lists_list')


class CardCreateView(LoginRequiredMixin, CreateView):
    model = Card
    template_name = 'kanban/cards/create.html'
    form_class = CardForm
    success_url = reverse_lazy('kanban:cards_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class CardListView(LoginRequiredMixin, ListView):
    model = Card
    template_name = 'kanban/cards/list.html'


class CardDetailView(LoginRequiredMixin, DetailView):
    model = Card
    template_name = 'kanban/cards/detail.html'


class CardUpdateView(LoginRequiredMixin, UpdateView):
    model = Card
    template_name = 'kanban/cards/update.html'
    form_class = CardForm

    def get_success_url(self):
        return resolve_url('kanban:cards_detail', pk=self.kwargs['pk'])


class CardDeleteView(LoginRequiredMixin, DeleteView):
    model = Card
    template_name = 'kanban/cards/delete.html'
    form_class = CardForm
    success_url = reverse_lazy('kanban:cards_list')

kanban/kanban/templates/kanban/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>kanban</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'kanban:index' %}">kanban</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
          </ul>
          <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'kanban:users_detail' request.user.pk %}">{{ request.user.username }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'kanban:lists_list' %}">リスト一覧</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">ログイン</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'kanban:signup' %}">サインアップ</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
  </body>
</html>

kanban/kanban/templates/kanban/cards/create.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>カード作成</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
  </form>
</div>
{% endblock %}

kanban/kanban/templates/kanban/cards/delete.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>カード削除</h1>
  <form method="post">
    {% csrf_token %}
    <p>カード "{{ card.title }}" を本当に削除してもよろしいですか？</p>
    <button type="submit" class="btn btn-danger">確認</button>
  </form>
</div>
{% endblock %}

kanban/kanban/templates/kanban/cards/detail.html
{% extends "kanban/base.html" %}

{% block content %}

<h1>カード詳細</h1>
<dl class="row">
  <dt class="col-sm-3">タイトル</dt>
  <dd class="col-sm-9">{{ card.title }}</dd>
  <dt class="col-sm-3">詳細</dt>
  <dd class="col-sm-9">{{ card.description }}</dd>
  <dt class="col-sm-3">リスト名</dt>
  <dd class="col-sm-9">{{ card.list.title }}</dd>
  <dt class="col-sm-3">ユーザー名</dt>
  <dd class="col-sm-9">{{ card.user.username }}</dd>
</dl>
<a class="btn btn-primary" href="{% url 'kanban:cards_update' card.pk  %}" role="button">編集</a>
<a class="btn btn-danger" href="{% url 'kanban:cards_delete' card.pk  %}" role="button">削除</a>

{% endblock %}

kanban/kanban/templates/kanban/cards/list.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>カード一覧</h1>
  <a class="btn btn-primary my-3" href="{% url 'kanban:cards_create' %}" role="button">作成</a>
  <div class="card-columns">
    {% for card in card_list %}
    <a href="{% url 'kanban:cards_detail' card.pk %}" class="card">
      <div class="card-body">
        <h5 class="card-title">{{ card.title }}</h5>
        <footer>
          <small class="text-muted">作成者: {{ card.user.username }}</small>
        </footer>
      </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock %}

kanban/kanban/templates/kanban/cards/update.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>カード編集</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
  </form>
</div>
{% endblock %}

kanban/kanban/templates/kanban/home.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>サインアップ完了</h1>
  <p>サインアップが完了しました。</p>
</div>
{% endblock %}

kanban/kanban/templates/kanban/index.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1 class="display-4">kanban</h1>
  <p class="lead">kanbanでタスク管理をしてみましょう。</p>
  <hr class="my-4">
  <p>このアプリケーションはDjangoで作られています。</p>
  <a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">ログイン</a>
  <a class="btn btn-primary btn-lg" href="{% url 'kanban:signup' %}" role="button">サインアップ</a>
</div>
{% endblock %}

kanban/kanban/templates/kanban/lists/create.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>リスト作成</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
  </form>
</div>
{% endblock %}

kanban/kanban/templates/kanban/lists/delete.html
{% extends "kanban/base.html" %}

{% block content %}
<h1>リスト削除</h1>
<form method="post">
  {% csrf_token %}
  <p>リスト "{{ list.title }}" を本当に削除してもよろしいですか？</p>
  <button type="submit" class="btn btn-danger">確認</button>
</form>
{% endblock %}

kanban/kanban/templates/kanban/lists/detail.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>リスト詳細</h1>
  <dl class="row">
    <dt class="col-sm-3">タイトル</dt>
    <dd class="col-sm-9">{{ list.title }}</dd>
    <dt class="col-sm-3">ユーザー名</dt>
    <dd class="col-sm-9">{{ list.user.username }}</dd>
  </dl>
  <a class="btn btn-primary" href="{% url 'kanban:lists_update' list.pk %}" role="button">編集</a>
  <a class="btn btn-danger" href="{% url 'kanban:lists_delete' list.pk %}" role="button">削除</a>
</div>
{% endblock %}

kanban/kanban/templates/kanban/lists/list.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>リスト一覧</h1>
  <a class="btn btn-primary my-3" href="{% url 'kanban:lists_create' %}" role="button">作成</a>
  <div class="card-columns">
    {% for list in list_list %}
    <a href="{% url 'kanban:lists_detail' list.pk %}" class="card">
      <div class="card-body">
        <h5 class="card-title">{{ list.title }}</h5>
        <footer>
          <small class="text-muted">作成者: {{ list.user.username }}</small>
        </footer>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

kanban/kanban/templates/kanban/lists/update.html
{% extends "kanban/base.html" %}

{% block content %}
<h1>リスト編集</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">送信</button>
</form>
{% endblock %}

kanban/kanban/templates/kanban/signup.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>サインアップ</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">登録</button>
  </form>
</div>
{% endblock %}

kanban/kanban/templates/kanban/users/detail.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>ユーザー詳細</h1>
    <dl class="row">
    <dt class="col-sm-3">ユーザー名</dt>
    <dd class="col-sm-9">{{ user.username }}</dd>
    <dt class="col-sm-3">姓</dt>
    <dd class="col-sm-9">{{ user.last_name }}</dd>
    <dt class="col-sm-3">名</dt>
    <dd class="col-sm-9">{{ user.first_name }}</dd>
    <dt class="col-sm-3">メールアドレス</dt>
    <dd class="col-sm-9">{{ user.email }}</dd>
  </dl>
  {% if user.pk == request.user.pk %}
  <a class="btn btn-primary" href="{% url 'kanban:users_update' user.pk  %}" role="button">編集</a>
  {% else %}
  <a class="btn btn-primary disabled" href="#" role="button">編集</a>
  {% endif %}
</div>
{% endblock %}

kanban/kanban/templates/kanban/users/update.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1>ユーザー編集</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
  </form>
</div>
{% endblock %}